title: GKing Productions
short_title: GKing Pro
description: We Make the Show Happen
baseurl:
permalink: "/:path/"
defaults:
  - scope:
      path: ""
    values:
      layout: page
collections:
  projects:
    output: true
    permalink: "/projects/:path/"
